name: auto format ts,js files
on:
  push:
    paths:
      - "**.ts"
      - "**.js"
    branches:
      - develop

jobs:
  deno-fmt:
    name: Deno fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno fmt
      - name: commit code changes
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --local user.email "action@github.com";
            git config --local user.name "GitHub Action";
            git add . -A && git commit -m "chore: auto format" && git push origin;
          else
            echo "No changes to commit";
          fi
