name: auto update readme
on:
  push:
    paths:
      - ecmascript/**
    branches:
      - develop

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: update readme
        run: bash scripts/update_readme.sh;
      - name: commit readme changes
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --local user.email "action@github.com";
            git config --local user.name "GitHub Action";
            git add . -A && git commit -m "chore: auto update readme" && git push origin;
          else
            echo "No changes to commit";
          fi
